resources:
- name: release-branch
  type: git
  # webhook_token: 7709991122
  source: &release-branch
    uri: git@github.com:newfloat/foobar-java.git
    branch: master
    private_key: {{github-private-key}}
  check_every: 1m

- name: slack
  type: slack-notification
  source:
    url: {{slack-webhook-url}}
  check_every: 5m

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

jobs:
- name: Version
  max_in_flight: 1
  plan:
  - get: release-branch
    trigger: true
  - task: Version
    file: release-branch/ci/github_version.yml
    input_mapping: {code-repo: release-branch}
    params:
      ENVIRONMENT: development
      GITHUB_PRIVATE_KEY: {{github-private-key}}
      GITHUB_TOKEN: {{github-token}}
      TRACKER_TOKEN: {{tracker-token}}
      SLACK_WEBHOOK_URL: {{slack-webhook-url}}
    on_failure:
      put: slack
      params:
        channel: "#test-feeds"
        username: concourse
        icon_url: https://avatars1.githubusercontent.com/u/7809479?v=3&s=200
        text: "$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME failed versioning! <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|  Click for details.>"
